version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - .github/actions/
      - .github/workflows/
    schedule:
      interval: weekly
    commit-message:
      prefix: 'ci(deps)'
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: bun
    directories:
      - packages/core/
      - site/
    schedule:
      interval: weekly
    commit-message:
      prefix: 'deps'
    labels:
      - dependencies
      - bun
